transaction:
  path_to_robonomics_file: "" #where lies the binaty file, ends with a binary filename
  remote: '' #e.g. '--remote ws://127.0.0.1:9944'
  address: '' #destination address in chain
  key: '' #sender key (raw seed)(to sign on and off transactions)
